defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400

development:
  <<: *defaults
  authenticators:
    -
      class: "CASinoCore::Authenticator::Static"
      options:
        users:
          testuser:
            password: "foobar123"
            name: "Test User"

test:
  <<: *defaults
  authenticators:
    -
      class: "CASinoCore::Authenticator::Static"
      options:
        users:
          testuser:
            password: "foobar123"
            name: "Test User"
